### ISSUE TITLE
License

### ISSUE THREAD

**Issue by julianchin** [mkheck/MonologFX#3]
Hello, 

Thanks for developing such a great library. My colleagues and I have been using MonologFX in a Java7 tool and we'd like to release the tool under GPLv3. We are wondering under what license MonologFX is provided? We'd like to make sure the license of MonologFX is compatible with GPLv3 (e.g. a GPLv3 license or Apache 2.0 License). 
Thank you!

Regards,
Julian

**Comment by hecklerm** [comment]
Hi Julian,

Thanks for the kind words! I didn't realize I hadn't put a license in the header - mea culpa. My intention has always been to provide the least restrictive and most practical license for the MonologFX code, and my understanding is that the MIT license (even more than the Apache license) satisfies that. I'll update the headers soon, but bottom line, a simple acknowledgement of my original copyright is truly all I ask. :)

Glad you like the library!

All the best,
Mark

**Comment by julianchin** [comment]
Hi Mark, 

Thanks so much for your prompt reply! The MIT license works perfect and it is compatible with the GNU GPL license we are going to use. We will definitely acknowledge your copyright in the license statement. Thanks again for your help!

Best regards,
Julian

**Comment by hecklerm** [comment]
Hi Julian,

You're very welcome, best of luck to you and your team!

All the best,
Mark
